const FILES_FETCH_REQUEST = 'FILES_FETCH_REQUEST';
const FILES_FETCH_RESPONSE = 'FILES_FETCH_RESPONSE';
const FILES_FETCH_FAILED = 'FILES_FETCH_FAILED';

const PASTE_DESTINATION_DIRECTORIES_FETCH_REQUEST =
  'PASTE_DESTINATION_DIRECTORIES_FETCH_REQUEST';
const PASTE_DESTINATION_DIRECTORIES_FETCH_RESPONSE =
  'PASTE_DESTINATION_DIRECTORIES_FETCH_RESPONSE';
const PASTE_DESTINATION_DIRECTORIES_FETCH_FAILED =
  'PASTE_DESTINATION_DIRECTORIES_FETCH_FAILED';

export {
  FILES_FETCH_REQUEST,
  FILES_FETCH_RESPONSE,
  FILES_FETCH_FAILED,
  PASTE_DESTINATION_DIRECTORIES_FETCH_REQUEST,
  PASTE_DESTINATION_DIRECTORIES_FETCH_RESPONSE,
  PASTE_DESTINATION_DIRECTORIES_FETCH_FAILED,
};
