const FILES_FETCH_REQUEST = 'FILES_FETCH_REQUEST';
const FILES_FETCH_RESPONSE = 'FILES_FETCH_RESPONSE';
const FILES_FETCH_FAILED = 'FILES_FETCH_FAILED';

const PASTE_DESTINATION_DIRECTORIES_FETCH_REQUEST =
  'PASTE_DESTINATION_DIRECTORIES_FETCH_REQUEST';
const PASTE_DESTINATION_DIRECTORIES_FETCH_RESPONSE =
  'PASTE_DESTINATION_DIRECTORIES_FETCH_RESPONSE';
const PASTE_DESTINATION_DIRECTORIES_FETCH_FAILED =
  'PASTE_DESTINATION_DIRECTORIES_FETCH_FAILED';

const CREATE_NEW_FILE_REQUEST = 'CREATE_NEW_FILE_REQUEST';
const CREATE_NEW_FILE_FAILED = 'CREATE_NEW_FILE_FAILED';
const CREATE_NEW_FILE_SUCCEDED = 'CREATE_NEW_FILE_SUCCEDED';

const SORT_FILES_REQUEST = 'SORT_FILES_REQUEST';
const SORT_FILES_FAILED = 'SORT_FILES_FAILED';
const SORT_FILES_SUCCEDED = 'SORT_FILES_SUCCEDED';

export {
  FILES_FETCH_REQUEST,
  FILES_FETCH_RESPONSE,
  FILES_FETCH_FAILED,
  PASTE_DESTINATION_DIRECTORIES_FETCH_REQUEST,
  PASTE_DESTINATION_DIRECTORIES_FETCH_RESPONSE,
  PASTE_DESTINATION_DIRECTORIES_FETCH_FAILED,
  CREATE_NEW_FILE_REQUEST,
  CREATE_NEW_FILE_FAILED,
  CREATE_NEW_FILE_SUCCEDED,
  SORT_FILES_REQUEST,
  SORT_FILES_FAILED,
  SORT_FILES_SUCCEDED,
};
